import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex gap-2 bg-red-200 p-3">
          <div className="flex flex-col justify-between bg-red-200 text-xs">
            <p>Mon</p>

            <p>Thu</p>

            <p>Sun</p>
          </div>
          <div className="grid-52-columns gap-[3px] ">
            {Array.from({ length: 364 }, (_, i) => (
              <div key={i} className="size-4 rounded-sm bg-red-500"></div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
